# Generated by Django 2.1.7 on 2019-06-08 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190608_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='contenido',
            field=models.TextField(default='hola', max_length=10000),
            preserve_default=False,
        ),
    ]
