# Generated by Django 2.1.7 on 2019-06-10 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20190610_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='idUsuario',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
