# Generated by Django 2.1.7 on 2019-06-11 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_dictauthor_dictsection_dictterm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dictterm',
            name='user',
        ),
        migrations.DeleteModel(
            name='Ocupacion',
        ),
        migrations.RemoveField(
            model_name='puntuacion',
            name='noticia',
        ),
        migrations.RemoveField(
            model_name='puntuacion',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='noticia',
            name='ratings',
        ),
        migrations.DeleteModel(
            name='DictTerm',
        ),
        migrations.DeleteModel(
            name='Puntuacion',
        ),
    ]
